### ISSUE TITLE
[DOCKER] env var overrides are applied on initial run, but not in subsequent scheduled runs

### ISSUE THREAD

**Issue by mgrimace** [TheNetsky/Microsoft-Rewards-Script#163]
Adding this issue for myself to fix, and anyone who is able to help on the docker end (pinging @MuhammadUsamaMX)

Not a breaking issue, and easily worked-around by using a persistent, volume-mapped config.json, which is good practice for docker implementation anyways.

**Issue:** As far as I can tell, using environmental variables as config.json overrides in the compose.yaml _do_ work as intended for the initial run of the script. However, it seems like the overrides may not persist on subsequent runs created with the in-built cronjob functionality. For example, I disabled doing punchcards only in my compose file (and not in my config.json), rebuilt the script. It ran fine for the first run, but the next scheduled run still attempted to do the punchcards. 

Likely this is an issue in my cronjob logic, and I'll have to play around. Again, I'm a novice, and PRs/contributions on the docker side of things are welcome + encouraged.

**Workaround**: use persistent volume mapping for config.json, and make sure all your preferences are set in config.json and not in the compose. Bonus, use mapped volumes for sessions and accounts for convenience. Sample below:

**compose.yaml**:

```yaml
services:
  microsoft-rewards-script:
    build: .
    container_name: netsky
    environment:
      - TZ=America/Toronto 
      - NODE_ENV=production 
      - HEADLESS=true
      - RUN_ON_START=true 
    volumes:
      - /root/docker/appdata/netsky/accounts.json:/usr/src/microsoft-rewards-script/dist/accounts.json
      - /root/docker/appdata/netsky/config.json:/usr/src/microsoft-rewards-script/dist/config.json
      - /root/docker/appdata/netsky/sessions:/usr/src/microsoft-rewards-script/dist/browser/sessions
    deploy:
      resources:
        limits:
          memory: 2048M    
    restart: unless-stopped
```

Note, you'd customize your own 'volumes' to wherever you want the persistent files to be stored on your host machine, where `./sessions:/usr/src/microsoft-rewards-script/dist/browser/sessions`would keep them in the same folder as your compose.yaml.

An alternative solution might be to strip the env var overrides and just use the volume mapping.
