### ISSUE TITLE
How much memory to allocate for 1.5 version

### ISSUE THREAD

**Issue by fengpan0403** [TheNetsky/Microsoft-Rewards-Script#242]
My VPS is 2GB memory. It's used up by the process.

**Comment by mgrimace** [comment]
I reserve 5g ram and it runs smoothly, for example, I deploy my docker container with the following parameters:

```
    deploy:
      resources:
        limits:
          cpus: "2.5"   # Allow up to 2.5 vCPUs
          memory: "5g"  # Cap memory at 5GB (leaving some free for LXC overhead)
        reservations:
          cpus: "1"      # Ensure at least 1 vCPU is always available
          memory: "2g"   # Ensure at least 2GB is always available
```
