### ISSUE TITLE
Excessive CPU/RAM use on 1.44

### ISSUE THREAD

**Issue by mgrimace** [TheNetsky/Microsoft-Rewards-Script#61]
Hello,
I'm on a fresh install of 1.4.4, headless, Debian Bookworm LXC with 4vCPU and 4gb Ram. The script is the only thing that runs, and after some period of use it seems to crash/stall the system at/near 100% CPU and RAM. 

I'm not sure how to diagnose or what would be useful, and no issue previously on 1.4.2
![Screenshot 2024-02-07 174046](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/55518507/c5870f92-68a0-42bc-a815-8bd14683826d)

Happy to run further tests, logs, etc.

**Comment by mgrimace** [comment]
I'll add that it ran unnatttended using cron and re-running via SSH (headless) now the issue seemed to have happened at some point during the searches.

**Comment by mgrimace** [comment]
Config:

```yaml
{
    "baseURL": "https://rewards.bing.com",
    "sessionPath": "sessions",
    "headless": true,
    "runOnZeroPoints": false,
    "clusters": 2,
    "saveFingerprint": false,
    "workers": {
        "doDailySet": true,
        "doMorePromotions": true,
        "doPunchCards": true,
        "doDesktopSearch": true,
        "doMobileSearch": true
    },
    "searchSettings": {
        "useGeoLocaleQueries": true,
        "scrollRandomResults": true,
        "clickRandomResults": true,
        "searchDelay": {
            "min": 180000,
            "max": 270000
        },
        "retryMobileSearch": true
    },
    "webhook": {
        "enabled": false,
        "url": ""
    }
}
```

The crontab entry that I use is: `10 7,13,19 * * * cd /root/Microsoft-Rewards-Script && npm run start`
